[default]
REQUEST_URL."習志野市" = "https://www.city.narashino.lg.jp/soshiki/kodomo_hoiku/gyomu/hoikugakko/akireigetu.html"
LINE_NOTIFY_API = "https://notify-api.line.me/api/notify"
SECRET_MANAGER_NAME = "LINE_NOTIFY"
LINE_NOTIFY_MAX_MESSAGE_LENGTH = 1000
TARGET_AGE = ["0歳児", "1歳児", "2歳児"]
TARGET_AVAILABILITY = ["1～2人", "3人以上"]

AVAILABILITY."◯" = "3人以上"
AVAILABILITY."△" = "1～2人"
AVAILABILITY."×" = "空きなし"
AVAILABILITY."―" = "受け入れなし"

[staging]
LINE_NOTIFY_TOKEN_ID = "line_notify_dev"
GCP_PROJECT_ID = "analysis-9en-stg"

[production]
LINE_NOTIFY_TOKEN_ID = "保育所等空き状況"
GCP_PROJECT_ID = "analysis-9en"
